# Generated by Django 5.1.6 on 2025-03-28 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_employee', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sales_revenue', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('version', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_global', models.FloatField()),
                ('score_axe_x', models.FloatField()),
                ('score_axe_y', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.axis')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.axis')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.survey')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.question')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='maturity_site.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('global_average', models.FloatField(blank=True, null=True)),
                ('average_axe_x', models.FloatField(blank=True, null=True)),
                ('average_axe_y', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.company')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.results'),
        ),
    ]
