# Generated by Django 5.1.6 on 2025-03-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='maturity_site.diagnostic')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.question')),
            ],
        ),
    ]
