# Generated by Django 5.1.6 on 2025-04-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0003_company_code_company_owner_results_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.IntegerField(default=1, help_text='Numéro de la page/Section'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='axe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maturity_site.axis'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='min_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maturity_site.question'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='type',
            field=models.CharField(blank=True, choices=[('axe', 'Based on axis/dimensions'), ('ecart', 'Based on a difference btw Manager/Employé'), ('question', 'Based on a low value answer')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity_site.axis')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maturity_site.dimension'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maturity_site.dimension'),
        ),
    ]
