# Generated by Django 5.1.6 on 2025-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0004_remove_question_title_question_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
