# Generated by Django 5.1.6 on 2025-04-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0006_remove_question_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='axe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maturity_site.axis'),
        ),
    ]
