# Generated by Django 5.1.6 on 2025-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0008_question_is_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('retail', 'Retail and Wholesale Trade'), ('it', ' Information and Communication Technology (ICT)'), ('proscitec', 'Professional, Scientific, and Technical Services'), ('finance', 'Finance and Insurance'), ('estate', 'Real Estate and Rental Services'), ('healthcare', 'Healthcare and Social Assistance'), ('accommodation', 'Accommodation and Food Services'), ('education', 'Education and Training'), ('transportation', 'Transportation and Logistics'), ('agriculture', 'Agriculture, Forestry, and Fishing'), ('arts', 'Arts, Entertainment, and Recreation'), ('administrative', 'Administrative and Support Services'), ('utilities', 'Utilities and Energy'), ('mining', 'Mining and Quarrying'), ('publicad', 'Public Administration'), ('waste', 'Waste Management and Remediation Services'), ('textiles', 'Textiles and Apparel'), ('other', 'Personal and Other Services')], max_length=100),
        ),
    ]
