# Generated by Django 5.1.6 on 2025-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0009_alter_company_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sales_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
