# Generated by Django 5.1.6 on 2025-04-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0011_alter_company_options_alter_company_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=100, null=True),
        ),
    ]
