# Generated by Django 5.1.6 on 2025-04-20 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0012_diagnostic_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
