# Generated by Django 5.1.6 on 2025-04-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0013_diagnostic_company_diagnostic_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='score_global',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
