# Generated by Django 5.1.6 on 2025-04-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0014_alter_diagnostic_score_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='score_axe_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='score_axe_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
