# Generated by Django 5.1.6 on 2025-04-20 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0015_alter_diagnostic_score_axe_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='axe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maturity_site.axis'),
        ),
    ]
