# Generated by Django 5.1.6 on 2025-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0019_recommendation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='template_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
