# Generated by Django 5.1.6 on 2025-04-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0020_recommendation_template_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='maturity_site.diagnostic'),
        ),
    ]
