# Generated by Django 5.1.6 on 2025-04-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_site', '0021_alter_recommendation_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sales_revenue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_answers', to='maturity_site.question'),
        ),
    ]
